sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 39.106.77.183
    port: 3306
    database: sky_take_out
    username: root
    password: 565034470
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMHJgr6
    access-key-id1: cdhZeC4sW5hU
    access-key-secret: Hv0t8CKG2FO8I
    access-key-secret1: IR28QhHNf0FpusiRg
    bucket-name: plumsnow